/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/free_merc_hovercar.glb 
Author: Karol Miklas (https://sketchfab.com/karolmiklas)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/free-merc-hovercar-oFfjKlslHqXgtKdKqEtpffmSv6h
Title: (FREE) Merc Hovercar
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function FreeCarTestModel(props) {
  const { nodes, materials } = useGLTF('/model/free_merc_hovercar.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.019, -0.066, -0.047]} rotation={[-Math.PI / 2, 0, 0]} scale={0.496}>
        <mesh geometry={nodes.Plane006_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane006_1.geometry} material={materials.Material_light} />
        <mesh geometry={nodes.Plane_0.geometry} material={materials.Plane_0} position={[0, 0, -0.582]} scale={[1.187, 2, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/free_merc_hovercar.glb')
